# Generated by Django 5.0.6 on 2024-05-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(verbose_name='Переменная')),
                ('text', models.CharField(max_length=20, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Содержимое бота',
                'verbose_name_plural': 'Содержимое бота',
            },
        ),
    ]
