# Generated by Django 5.0.6 on 2024-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='Переменная')),
                ('text', models.CharField(max_length=20, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
            },
        ),
        migrations.AlterModelOptions(
            name='buttons',
            options={'verbose_name': 'Кнопка бота', 'verbose_name_plural': 'Кнопки бота'},
        ),
        migrations.AlterField(
            model_name='buttons',
            name='variable',
            field=models.CharField(max_length=255, verbose_name='Переменная'),
        ),
    ]
