# Generated by Django 5.0.6 on 2024-05-19 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_bouquettype_flowercolor_flowersubtype_flowertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquettype',
            options={'verbose_name': 'Тип букета', 'verbose_name_plural': 'Типы букетов'},
        ),
        migrations.AlterModelOptions(
            name='flowercolor',
            options={'verbose_name': 'Цвет цветка', 'verbose_name_plural': 'Цвета цветков'},
        ),
        migrations.AlterModelOptions(
            name='flowersubtype',
            options={'verbose_name': 'Подтип цветка', 'verbose_name_plural': 'Подтипы цветков'},
        ),
        migrations.AlterModelOptions(
            name='flowertype',
            options={'verbose_name': 'Тип цветка', 'verbose_name_plural': 'Типы цветков'},
        ),
        migrations.AddField(
            model_name='flowercolor',
            name='flower_subtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='AdminPanel.flowersubtype', verbose_name='Подтип цветка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowersubtype',
            name='flower_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='AdminPanel.flowertype', verbose_name='Тип цветка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowertype',
            name='bouquet_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flower_types', to='AdminPanel.bouquettype', verbose_name='Тип букета'),
            preserve_default=False,
        ),
    ]
