# Generated by Django 5.0.6 on 2024-05-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_alter_bouquettype_options_alter_flowercolor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowersubtype',
            options={'verbose_name': 'Подвид цветка', 'verbose_name_plural': 'Подвиды цветков'},
        ),
        migrations.AddField(
            model_name='flowercolor',
            name='flower_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='AdminPanel.flowertype'),
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='flower_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='AdminPanel.flowersubtype', verbose_name='Подтип цветка'),
        ),
        migrations.AlterField(
            model_name='flowersubtype',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
    ]
