# Generated by Django 5.0.6 on 2024-05-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_remove_bouquettype_use_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='Переменная')),
                ('text', models.CharField(max_length=20, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Списки бота',
                'verbose_name_plural': 'Списки бота',
            },
        ),
        migrations.RemoveField(
            model_name='flowercolor',
            name='flower_type',
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='flower_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='AdminPanel.flowersubtype', verbose_name='Подтип цветка'),
        ),
        migrations.AlterField(
            model_name='flowersubtype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
