# Generated by Django 5.0.6 on 2024-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_lists_remove_flowercolor_flower_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Раздел бота')),
            ],
            options={
                'verbose_name': 'Раздел бота',
                'verbose_name_plural': 'Разделы бота',
            },
        ),
    ]
