# Generated by Django 5.0.6 on 2024-05-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
