# Generated by Django 5.0.6 on 2024-05-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_buttons_category_lists_category_messages_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttons',
            name='screen',
            field=models.IntegerField(default=1, verbose_name='Экран'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buttons',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories', verbose_name='Раздел'),
        ),
    ]
