# Generated by Django 5.0.6 on 2024-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_buttons_screen_alter_buttons_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='screen',
            field=models.IntegerField(default=1, verbose_name='Экран'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='screen',
            field=models.IntegerField(default=1, verbose_name='Экран'),
            preserve_default=False,
        ),
    ]
