# Generated by Django 5.0.6 on 2024-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_lists_screen_messages_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Значение'),
        ),
    ]
