# Generated by Django 5.0.6 on 2024-05-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_alter_messages_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name': 'Список бота', 'verbose_name_plural': 'Списки бота'},
        ),
        migrations.AlterField(
            model_name='buttons',
            name='text',
            field=models.CharField(help_text='Максимальное количество символов: 20', max_length=20, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='text',
            field=models.CharField(help_text='Максимальное количество символов: 20', max_length=20, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(help_text='Максимальное количество символов: 1024', max_length=1024, verbose_name='Значение'),
        ),
        migrations.CreateModel(
            name='ListTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='Переменная')),
                ('text', models.CharField(help_text='Максимальное количество символов: 20', max_length=20, verbose_name='Значение')),
                ('screen', models.IntegerField(verbose_name='Экран')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Заголовок списка',
                'verbose_name_plural': 'Заголовки списков',
            },
        ),
    ]
