# Generated by Django 5.0.6 on 2024-06-06 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0015_alter_lists_options_alter_buttons_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='Переменная')),
                ('text', models.CharField(verbose_name='Значение')),
                ('screen', models.IntegerField(verbose_name='Экран')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Системная переменная',
                'verbose_name_plural': 'Системные переменные',
            },
        ),
    ]
